// Code generated by go generate; DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"

	"github.com/OpenSyntaxHQ/tweak/processors"
	"github.com/OpenSyntaxHQ/tweak/utils"
	"github.com/spf13/cobra"
)

var (	
	checksumVerify_flag_x string	
	checksumVerify_flag_g string
)

func init() {
	checksumVerifyCmd.Flags().StringVarP(&checksumVerify_flag_x, "hash", "x", "", "Expected hash to verify against")
	checksumVerifyCmd.Flags().StringVarP(&checksumVerify_flag_g, "algo", "g", "sha256", "Hash algorithm (md5/sha1/sha256/sha384/sha512)")
	_ = checksumVerifyCmd.MarkFlagRequired("hash")
	rootCmd.AddCommand(checksumVerifyCmd)
}

var checksumVerifyCmd = &cobra.Command{
	Use:     "checksum-verify [string]",
	Short:   "Verify checksum against expected hash",
	Aliases: []string{"verify-hash", "check-hash"},
	Args:    cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var err error
		var out string
		var in []byte

		flags := make([]processors.Flag, 0)
		p := processors.ChecksumVerify{}
		flags = append(flags, processors.Flag{Short: "x", Value: checksumVerify_flag_x})
		flags = append(flags, processors.Flag{Short: "g", Value: checksumVerify_flag_g})

		if processors.IsGenerator(p) {
			out, err = p.Transform(nil, flags...)
			if err != nil {
				return err
			}
		} else if utils.StdinHasData() {
			in, err = utils.ReadPipedInput()
			if err != nil {
				return err
			}
			out, err = p.Transform(in, flags...)
			if err != nil {
				return err
			}
		} else if len(args) > 0 {
			if fi, statErr := os.Stat(args[0]); statErr == nil && !fi.IsDir() {
				const largeFileThreshold = 10 * 1024 * 1024 // 10 MiB

				if processors.ShouldStream(p, fi.Size(), largeFileThreshold) {
					file, fErr := os.Open(args[0])
					if fErr != nil {
						return fErr
					}
					defer file.Close()
					return processors.TransformStream(p, file, os.Stdout, flags...)
				}

				d, rErr := os.ReadFile(args[0])
				if rErr != nil {
					return rErr
				}
				out, err = p.Transform(d, flags...)
				if err != nil {
					return err
				}
			} else {
				out, err = p.Transform([]byte(args[0]), flags...)
				if err != nil {
					return err
				}
			}
		} else {
			in = []byte(utils.ReadMultilineInput())
			out, err = p.Transform(in, flags...)
			if err != nil {
				return err
			}
		}

		_, err = fmt.Fprint(os.Stdout, out)
		return err
	},
}
