// Code generated by go generate; DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"

	"github.com/OpenSyntaxHQ/tweak/processors"
	"github.com/OpenSyntaxHQ/tweak/utils"
	"github.com/spf13/cobra"
)

var (	
	qr_flag_s uint	
	qr_flag_l string	
	qr_flag_f bool
)

func init() {	
	qrCmd.Flags().UintVarP(&qr_flag_s, "size", "s", 100, "QR code size hint")
	qrCmd.Flags().StringVarP(&qr_flag_l, "level", "l", "H", "Error correction level (L/M/H)")	
	qrCmd.Flags().BoolVarP(&qr_flag_f, "full", "f", false, "Use full blocks")
	rootCmd.AddCommand(qrCmd)
}

var qrCmd = &cobra.Command{
	Use:     "qr [string]",
	Short:   "Generate QR code in terminal",
	Aliases: []string{"qrcode", "qr-code"},
	Args:    cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var err error
		var out string
		var in []byte

		flags := make([]processors.Flag, 0)
		p := processors.QRCode{}
		flags = append(flags, processors.Flag{Short: "s", Value: qr_flag_s})
		flags = append(flags, processors.Flag{Short: "l", Value: qr_flag_l})
		flags = append(flags, processors.Flag{Short: "f", Value: qr_flag_f})

		if processors.IsGenerator(p) {
			out, err = p.Transform(nil, flags...)
			if err != nil {
				return err
			}
		} else if utils.StdinHasData() {
			in, err = utils.ReadPipedInput()
			if err != nil {
				return err
			}
			out, err = p.Transform(in, flags...)
			if err != nil {
				return err
			}
		} else if len(args) > 0 {
			if fi, statErr := os.Stat(args[0]); statErr == nil && !fi.IsDir() {
				const largeFileThreshold = 10 * 1024 * 1024 // 10 MiB

				if processors.CanStream(p) && (fi.Size() > largeFileThreshold || processors.PreferStream(p)) {
					file, fErr := os.Open(args[0])
					if fErr != nil {
						return fErr
					}
					defer file.Close()
					return processors.TransformStream(p, file, os.Stdout, flags...)
				}

				d, rErr := os.ReadFile(args[0])
				if rErr != nil {
					return rErr
				}
				out, err = p.Transform(d, flags...)
				if err != nil {
					return err
				}
			} else {
				out, err = p.Transform([]byte(args[0]), flags...)
				if err != nil {
					return err
				}
			}
		} else {
			in = []byte(utils.ReadMultilineInput())
			out, err = p.Transform(in, flags...)
			if err != nil {
				return err
			}
		}

		_, err = fmt.Fprint(os.Stdout, out)
		return err
	},
}
