// Code generated by go generate; DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"

	"github.com/OpenSyntaxHQ/tweak/processors"
	"github.com/OpenSyntaxHQ/tweak/utils"
	"github.com/spf13/cobra"
)

var (	
	column_flag_f uint	
	column_flag_d string
)

func init() {	
	columnCmd.Flags().UintVarP(&column_flag_f, "field", "f", 1, "Field number (1-based)")
	columnCmd.Flags().StringVarP(&column_flag_d, "delimiter", "d", "", "Field delimiter (whitespace if empty)")
	rootCmd.AddCommand(columnCmd)
}

var columnCmd = &cobra.Command{
	Use:     "column [string]",
	Short:   "Extract column/field from text",
	Aliases: []string{"col", "field"},
	Args:    cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var err error
		var out string
		var in []byte

		flags := make([]processors.Flag, 0)
		p := processors.Column{}
		flags = append(flags, processors.Flag{Short: "f", Value: column_flag_f})
		flags = append(flags, processors.Flag{Short: "d", Value: column_flag_d})

		if processors.IsGenerator(p) {
			out, err = p.Transform(nil, flags...)
			if err != nil {
				return err
			}
		} else if utils.StdinHasData() {
			in, err = utils.ReadPipedInput()
			if err != nil {
				return err
			}
			out, err = p.Transform(in, flags...)
			if err != nil {
				return err
			}
		} else if len(args) > 0 {
			if fi, statErr := os.Stat(args[0]); statErr == nil && !fi.IsDir() {
				const largeFileThreshold = 10 * 1024 * 1024 // 10 MiB

				if processors.CanStream(p) && (fi.Size() > largeFileThreshold || processors.PreferStream(p)) {
					file, fErr := os.Open(args[0])
					if fErr != nil {
						return fErr
					}
					defer file.Close()
					return processors.TransformStream(p, file, os.Stdout, flags...)
				}

				d, rErr := os.ReadFile(args[0])
				if rErr != nil {
					return rErr
				}
				out, err = p.Transform(d, flags...)
				if err != nil {
					return err
				}
			} else {
				out, err = p.Transform([]byte(args[0]), flags...)
				if err != nil {
					return err
				}
			}
		} else {
			in = []byte(utils.ReadMultilineInput())
			out, err = p.Transform(in, flags...)
			if err != nil {
				return err
			}
		}

		_, err = fmt.Fprint(os.Stdout, out)
		return err
	},
}
