// Code generated by go generate; DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"

	"github.com/OpenSyntaxHQ/tweak/processors"
	"github.com/OpenSyntaxHQ/tweak/utils"
	"github.com/spf13/cobra"
)

var (	
	epoch_flag_f string	
	epoch_flag_z string
)

func init() {
	epochCmd.Flags().StringVarP(&epoch_flag_f, "format", "f", "2006-01-02 15:04:05 MST", "Output date format (Go layout)")
	epochCmd.Flags().StringVarP(&epoch_flag_z, "timezone", "z", "Local", "Timezone (e.g. UTC, America/New_York)")
	rootCmd.AddCommand(epochCmd)
}

var epochCmd = &cobra.Command{
	Use:     "epoch [string]",
	Short:   "Convert epoch ↔ human-readable timestamp",
	Aliases: []string{"timestamp", "ts"},
	Args:    cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var err error
		var out string
		var in []byte

		flags := make([]processors.Flag, 0)
		p := processors.Epoch{}
		flags = append(flags, processors.Flag{Short: "f", Value: epoch_flag_f})
		flags = append(flags, processors.Flag{Short: "z", Value: epoch_flag_z})

		if processors.IsGenerator(p) {
			out, err = p.Transform(nil, flags...)
			if err != nil {
				return err
			}
		} else if utils.StdinHasData() {
			in, err = utils.ReadPipedInput()
			if err != nil {
				return err
			}
			out, err = p.Transform(in, flags...)
			if err != nil {
				return err
			}
		} else if len(args) > 0 {
			if fi, statErr := os.Stat(args[0]); statErr == nil && !fi.IsDir() {
				const largeFileThreshold = 10 * 1024 * 1024 // 10 MiB

				if processors.ShouldStream(p, fi.Size(), largeFileThreshold) {
					file, fErr := os.Open(args[0])
					if fErr != nil {
						return fErr
					}
					defer file.Close()
					return processors.TransformStream(p, file, os.Stdout, flags...)
				}

				d, rErr := os.ReadFile(args[0])
				if rErr != nil {
					return rErr
				}
				out, err = p.Transform(d, flags...)
				if err != nil {
					return err
				}
			} else {
				out, err = p.Transform([]byte(args[0]), flags...)
				if err != nil {
					return err
				}
			}
		} else {
			in = []byte(utils.ReadMultilineInput())
			out, err = p.Transform(in, flags...)
			if err != nil {
				return err
			}
		}

		_, err = fmt.Fprint(os.Stdout, out)
		return err
	},
}
