// Code generated by go generate; DO NOT EDIT.

package cmd

import (
	"fmt"
	"os"

	"github.com/OpenSyntaxHQ/tweak/processors"
	"github.com/OpenSyntaxHQ/tweak/utils"
	"github.com/spf13/cobra"
)

var (	
	argon2_flag_s string	
	argon2_flag_t uint	
	argon2_flag_m uint
)

func init() {
	argon2Cmd.Flags().StringVarP(&argon2_flag_s, "salt", "s", "", "Salt string (random if omitted)")	
	argon2Cmd.Flags().UintVarP(&argon2_flag_t, "time", "t", 3, "Time parameter (iterations)")	
	argon2Cmd.Flags().UintVarP(&argon2_flag_m, "memory", "m", 65536, "Memory parameter in KiB")
	rootCmd.AddCommand(argon2Cmd)
}

var argon2Cmd = &cobra.Command{
	Use:     "argon2 [string]",
	Short:   "Argon2id password hash",
	Aliases: []string{"argon2id"},
	Args:    cobra.MaximumNArgs(1),
	RunE: func(cmd *cobra.Command, args []string) error {
		var err error
		var out string
		var in []byte

		flags := make([]processors.Flag, 0)
		p := processors.Argon2Hash{}
		flags = append(flags, processors.Flag{Short: "s", Value: argon2_flag_s})
		flags = append(flags, processors.Flag{Short: "t", Value: argon2_flag_t})
		flags = append(flags, processors.Flag{Short: "m", Value: argon2_flag_m})

		if processors.IsGenerator(p) {
			out, err = p.Transform(nil, flags...)
			if err != nil {
				return err
			}
		} else if utils.StdinHasData() {
			in, err = utils.ReadPipedInput()
			if err != nil {
				return err
			}
			out, err = p.Transform(in, flags...)
			if err != nil {
				return err
			}
		} else if len(args) > 0 {
			if fi, statErr := os.Stat(args[0]); statErr == nil && !fi.IsDir() {
				const largeFileThreshold = 10 * 1024 * 1024 // 10 MiB

				if processors.ShouldStream(p, fi.Size(), largeFileThreshold) {
					file, fErr := os.Open(args[0])
					if fErr != nil {
						return fErr
					}
					defer file.Close()
					return processors.TransformStream(p, file, os.Stdout, flags...)
				}

				d, rErr := os.ReadFile(args[0])
				if rErr != nil {
					return rErr
				}
				out, err = p.Transform(d, flags...)
				if err != nil {
					return err
				}
			} else {
				out, err = p.Transform([]byte(args[0]), flags...)
				if err != nil {
					return err
				}
			}
		} else {
			in = []byte(utils.ReadMultilineInput())
			out, err = p.Transform(in, flags...)
			if err != nil {
				return err
			}
		}

		_, err = fmt.Fprint(os.Stdout, out)
		return err
	},
}
